services:
  app:
    build: 
      context: .
    ports: 
      - "8000:8000"
    volumes:
      - ./app:/app  # Syncs local app changes with the container
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
