---
name: checks

on: [push]

jobs: 
    test-lint:
      name: Test and Lint
      runs-on: ubuntu-20.04  # use this verion of os to run 
      steps : 
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{secrets.DOCKERHUB__USER}} 
            password: ${{secrets.DOCKERHUB__TOKEN}} 
        - name: Checkout
          uses: actions/checkout@v2
        - name: Test
          run: docker-compose run --rm app sh -c "python manage.py test"
          